---
baseurl: http://hoffis-eck.de/guido/
disableKinds:
- taxonomy
- taxonomyTerm
- RSS
- sitemap
defaultContentLanguage: de
languageCode: de-de
title: Therapie Lindner
theme: Guido
enableRobotsTXT: true
pluralizelisttitles: false
params:
  image: fluss
