---
baseurl: http://hoffis-eck.de/Guido/
disableKinds:
- taxonomy
- taxonomyTerm
- RSS
- sitemap
defaultContentLanguage: de
languageCode: de-de
title: Sprechen mit Guido
theme: Guido
enableRobotsTXT: true
pluralizelisttitles: false
params:
  image: fluss
