baseurl: http://therapie-lindner.de/
disableKinds:
 - taxonomy
 - taxonomyTerm
 - RSS
 - sitemap
defaultContentLanguage:  de
languageCode: de-de
title: Therapie Lindner
theme: guido
enableRobotsTXT: true
pluralizelisttitles: false
params:
  image: fluss
